name: Deploy to Azure VM

on:
  push:
    branches:
      - main  # Change this to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3.12-venv
        python3 -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt

    - name: Deploy to Azure VM
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USER }}
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        port: 22
        script: |
          cd ~/chatroom-redes
          git pull origin main
          sudo apt update
          sudo apt install -y python3.12-venv
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
          nohup python server.py 0.0.0.0 8000 &
